# Generated by Django 5.1.2 on 2024-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_en_inventario', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('reparaciones', models.ManyToManyField(blank=True, related_name='repuestos', to='principal.reparacion')),
            ],
        ),
    ]
